# reports/latex_exporter.py
# ─────────────────────────────────────────────────────────────
# Generates a LaTeX (.tex) report — drop into Overleaf or run
# with pdflatex locally. Plots are embedded as base64 PNG via
# the LaTeX `graphicx` + includegraphics approach; alternatively
# the user can extract the \includegraphics paths and add the
# PNGs manually if they prefer.
# Returns (bytes, filename) ready for st.download_button.
# ─────────────────────────────────────────────────────────────

import io
import base64
import zipfile
import re

from reports.report_builder import build_report_payload


def _escape(text: str) -> str:
    """Escape special LaTeX characters in plain text strings."""
    replacements = [
        ("\\", "\\textbackslash{}"),
        ("&",  "\\&"),
        ("%",  "\\%"),
        ("$",  "\\$"),
        ("#",  "\\#"),
        ("_",  "\\_"),
        ("{",  "\\{"),
        ("}",  "\\}"),
        ("~",  "\\textasciitilde{}"),
        ("^",  "\\textasciicircum{}"),
    ]
    for old, new in replacements:
        text = text.replace(old, new)
    return text


def _metrics_tabular(metrics: dict) -> str:
    """Return a LaTeX tabular block for a single run's metrics."""
    rows = [
        ("R\\textsuperscript{2}", f"{metrics.get('R2',  0):.4f}"),
        ("RMSE",                  f"{metrics.get('RMSE', 0):.4f}"),
        ("MAE",                   f"{metrics.get('MAE',  0):.4f}"),
        ("MSE",                   f"{metrics.get('MSE',  0):.6f}"),
    ]
    lines = [
        r"\begin{tabular}{ll}",
        r"\toprule",
        r"\textbf{Metric} & \textbf{Value} \\",
        r"\midrule",
    ]
    for metric, val in rows:
        lines.append(f"{metric} & {val} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines)


def _comparison_tabular(comparison_rows: list[dict]) -> str:
    """Return a LaTeX longtable for the multi-run comparison."""
    if not comparison_rows:
        return ""
    headers = list(comparison_rows[0].keys())
    col_spec = "l" * len(headers)

    lines = [
        r"\begin{longtable}{" + col_spec + r"}",
        r"\toprule",
        " & ".join(f"\\textbf{{{_escape(str(h))}}}" for h in headers) + r" \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        " & ".join(f"\\textbf{{{_escape(str(h))}}}" for h in headers) + r" \\",
        r"\midrule",
        r"\endhead",
        r"\midrule",
        r"\multicolumn{" + str(len(headers)) + r"}{r}{\textit{Continued\ldots}} \\",
        r"\endfoot",
        r"\bottomrule",
        r"\endlastfoot",
    ]
    for row in comparison_rows:
        lines.append(" & ".join(_escape(str(v)) for v in row.values()) + r" \\")
    lines.append(r"\end{longtable}")
    return "\n".join(lines)


# ── Main template ──────────────────────────────────────────

def _build_tex(payload: dict, image_paths: dict) -> str:
    """
    Build the full .tex document string.

    image_paths : {plot_key: "figures/runN_plottype.png"} — paths
                  that will exist in the zip alongside the .tex file.
    """
    meta    = payload["meta"]
    profile = payload["profile"]
    runs    = payload["runs"]

    title       = _escape(meta.get("title",       "MLForge Training Report"))
    author      = _escape(meta.get("author",       ""))
    institution = _escape(meta.get("institution",  ""))
    date        = _escape(meta.get("date",         ""))
    notes       = _escape(meta.get("notes",        ""))

    dataset_name = _escape(runs[0].get("dataset_name", "Unknown") if runs else "Unknown")
    target_col   = _escape(runs[0].get("target_col",   "target")  if runs else "target")

    lines = [
        r"\documentclass[12pt,a4paper]{article}",
        r"\usepackage[T1]{fontenc}",
        r"\usepackage[utf8]{inputenc}",
        r"\usepackage{lmodern}",
        r"\usepackage[margin=2.5cm]{geometry}",
        r"\usepackage{graphicx}",
        r"\usepackage{booktabs}",
        r"\usepackage{longtable}",
        r"\usepackage{hyperref}",
        r"\usepackage{xcolor}",
        r"\usepackage{titlesec}",
        r"\usepackage{parskip}",
        r"",
        r"\definecolor{accent}{RGB}{79,134,198}",
        r"\definecolor{muted}{RGB}{107,123,141}",
        r"",
        r"\titleformat{\section}{\large\bfseries\color{black}}{\thesection}{1em}{}",
        r"    [\color{accent}\titlerule[1pt]]",
        r"\titleformat{\subsection}{\normalsize\bfseries\color{accent}}{\thesubsection}{1em}{}",
        r"",
        r"\hypersetup{colorlinks=true, linkcolor=accent, urlcolor=accent, citecolor=accent}",
        r"",
        r"\begin{document}",
        r"",
        r"\begin{titlepage}",
        r"\centering",
        r"\vspace*{3cm}",
        r"{\Huge\bfseries " + title + r" \par}",
        r"\vspace{0.5cm}",
        r"{\large\itshape\color{muted} Generated by MLForge --- Universal ML Training Platform \par}",
        r"\vspace{1.5cm}",
    ]

    if author:
        lines.append(r"{\large \textbf{Author:} " + author + r" \par}")
        lines.append(r"\vspace{0.3cm}")
    if institution:
        lines.append(r"{\large \textbf{Institution:} " + institution + r" \par}")
        lines.append(r"\vspace{0.3cm}")
    if date:
        lines.append(r"{\large \textbf{Date:} " + date + r" \par}")

    lines += [
        r"\end{titlepage}",
        r"",
        r"\tableofcontents",
        r"\newpage",
        r"",
        r"\section{Introduction}",
        r"",
        r"This report was generated by \textbf{MLForge}, a supervised regression "
        r"training platform supporting SVR (sklearn and hand-coded implementations), "
        r"Random Forest, MLP, Gradient Boosting, Ridge, ElasticNet, and K-Nearest "
        r"Neighbours regressors.",
        r"",
    ]

    if notes:
        lines.append(notes)
        lines.append("")

    # ── Dataset summary ────────────────────────────────────
    lines += [
        r"\section{Dataset Summary}",
        r"",
        r"\begin{tabular}{ll}",
        r"\toprule",
        r"\textbf{Property} & \textbf{Value} \\",
        r"\midrule",
        f"Dataset & {dataset_name} \\\\",
    ]

    if profile:
        lines += [
            f"Rows & {profile.get('n_rows', '---'):,} \\\\",
            f"Columns & {profile.get('n_cols', '---')} \\\\",
            f"Features (numeric) & {profile.get('n_features', '---')} \\\\",
            f"Missing values & {profile.get('missing_pct', 0):.1f}\\% \\\\",
            f"Time-series & {'Yes' if profile.get('is_time_series') else 'No'} \\\\",
            f"Target column & {target_col} \\\\",
        ]

    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"",
    ]

    if profile:
        for w in profile.get("warnings", []):
            clean_w = _escape(re.sub(r"[⚠️ℹ️]", "", w).strip())
            lines.append(r"\textcolor{orange}{\textit{Warning: " + clean_w + r"}}")
            lines.append("")

    # ── Model results ──────────────────────────────────────
    lines += [r"\section{Model Results}", r""]

    for run in runs:
        run_id    = run.get("run_id", "?")
        model_lbl = _escape(run.get("model_label", "Unknown"))
        metrics   = run.get("metrics", {})
        an        = run.get("analysis", {})
        bp        = run.get("best_params")

        lines += [
            f"\\subsection{{Run \\#{run_id} --- {model_lbl}}}",
            r"",
            _metrics_tabular(metrics),
            r"",
        ]

        if an.get("summary_sentence"):
            lines.append(_escape(an["summary_sentence"]))
            lines.append("")

        if an.get("mae_context"):
            lines.append(r"\textit{\small " + _escape(an["mae_context"]) + r"}")
            lines.append("")

        if an.get("recommendations"):
            lines.append(r"\textbf{Recommendations:}")
            lines.append(r"\begin{itemize}")
            for rec in an["recommendations"]:
                lines.append(r"  \item " + _escape(rec))
            lines.append(r"\end{itemize}")
            lines.append("")

        if bp:
            lines.append(r"\textit{Auto-tuned parameters: " + _escape(str(bp)) + r"}")
            lines.append("")

        # Figures
        for plot_type, caption in [
            ("actual_vs_predicted", "Actual vs Predicted values on test set"),
            ("residuals",           "Residual distribution"),
        ]:
            key = f"run{run_id}_{plot_type}"
            if key in image_paths:
                lines += [
                    r"\begin{figure}[h!]",
                    r"\centering",
                    r"\includegraphics[width=0.92\textwidth]{" + image_paths[key] + r"}",
                    r"\caption{" + _escape(caption) + r"}",
                    r"\end{figure}",
                    r"",
                ]

    # ── Comparison table ───────────────────────────────────
    if len(runs) > 1:
        lines += [r"\section{Runs Comparison}", r""]
        lines.append(_comparison_tabular(payload["comparison_rows"]))
        lines.append("")

        key = "comparison_chart"
        if key in image_paths:
            lines += [
                r"\begin{figure}[h!]",
                r"\centering",
                r"\includegraphics[width=0.88\textwidth]{" + image_paths[key] + r"}",
                r"\caption{R\textsuperscript{2} comparison across all runs}",
                r"\end{figure}",
                r"",
            ]

    # ── Conclusions ────────────────────────────────────────
    lines += [r"\section{Conclusions}", r""]

    best = payload.get("best_run")
    if best:
        bm    = best.get("metrics", {})
        b_lbl = _escape(best.get("model_label", ""))
        lines.append(
            f"The best-performing model was \\textbf{{{b_lbl}}} with "
            f"R\\textsuperscript{{2}} = {bm.get('R2',0):.4f}, "
            f"RMSE = {bm.get('RMSE',0):.4f}, "
            f"MAE = {bm.get('MAE',0):.4f}."
        )
        lines.append("")
        recs = best.get("analysis", {}).get("recommendations", [])
        if recs:
            lines.append(r"\begin{itemize}")
            for r in recs[:3]:
                lines.append(r"  \item " + _escape(r))
            lines.append(r"\end{itemize}")
            lines.append("")

    # ── References ────────────────────────────────────────
    lines += [
        r"\section{References}",
        r"",
        r"\begin{enumerate}",
        r"  \item \textbf{Goldrick et al., 2019} --- Modern day monitoring and control "
        r"challenges outlined on an industrial-scale benchmark fermentation process. "
        r"\textit{Computers \& Chemical Engineering}, 130, 106471. "
        r"\url{https://doi.org/10.1016/j.compchemeng.2019.05.037}",
        r"  \item \textbf{Cortes \& Vapnik, 1995} --- Support-Vector Networks. "
        r"\textit{Machine Learning}, 20(3), 273--297.",
        r"  \item \textbf{scikit-learn} --- Pedregosa et al. (2011). Scikit-learn: "
        r"Machine Learning in Python. \textit{JMLR} 12, 2825--2830.",
        r"  \item \textbf{Optuna} --- Akiba et al. (2019). Optuna: A Next-generation "
        r"Hyperparameter Optimization Framework. \textit{KDD 2019}.",
        r"\end{enumerate}",
        r"",
        r"\end{document}",
    ]

    return "\n".join(lines)


# ── Public entry point ─────────────────────────────────────

def build_latex(
    runs:            list[dict],
    report_cfg:      dict,
    dataset_profile: dict,
    ai_sections:     dict | None = None,
) -> tuple[bytes, str]:
    """
    Build a LaTeX report and return (zip_bytes, filename).
    """
    payload     = build_report_payload(runs, report_cfg, dataset_profile, ai_sections)
    image_paths = {}    # key → relative path used in \includegraphics
    image_data  = {}    # key → PNG bytes

    # ── Collect plot buffers ───────────────────────────────
    for run in payload["runs"]:
        rid  = run.get("run_id", "?")
        bufs = run.get("plot_bufs", {})

        for plot_type in ("actual_vs_predicted", "residuals"):
            buf = bufs.get(plot_type)
            if buf is not None:
                key  = f"run{rid}_{plot_type}"
                path = f"figures/{key}.png"
                buf.seek(0)
                image_data[key]  = buf.read()
                image_paths[key] = path

    comp_buf = payload.get("comp_plot_buf")
    if comp_buf is not None:
        comp_buf.seek(0)
        image_data["comparison_chart"]  = comp_buf.read()
        image_paths["comparison_chart"] = "figures/comparison_chart.png"

    # ── Build .tex string ──────────────────────────────────
    tex_str = _build_tex(payload, image_paths)

    # ── Pack into zip ──────────────────────────────────────
    zip_buf = io.BytesIO()
    with zipfile.ZipFile(zip_buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("report.tex", tex_str.encode("utf-8"))
        for key, png_bytes in image_data.items():
            zf.writestr(image_paths[key], png_bytes)

    zip_buf.seek(0)

    meta       = payload["meta"]
    safe_title = meta.get("title", "MLForge_Report").replace(" ", "_")
    filename   = f"{safe_title}_LaTeX.zip"

    return zip_buf.getvalue(), filename
