# reports/pdf_exporter.py
# ─────────────────────────────────────────────────────────────
# Generates a PDF report via an HTML template rendered with
# Jinja2 and converted by WeasyPrint.
# Returns (bytes, filename) ready for st.download_button.
# ─────────────────────────────────────────────────────────────

import io
import base64
from jinja2    import Template
from weasyprint import HTML

from reports.report_header_helper import report_header_html
from reports.report_builder import build_report_payload

# CHANGE 1: Added imports for logo and running header
from reports.report_header_helper import (
    pdf_cover_logo_html,
    pdf_running_header_html,
)

# ── HTML template ──────────────────────────────────────────
# Inline template — no external file dependency.
_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<style>
  /* CHANGE 2: Replaced @page CSS block */
  @page {
    size: A4;
    margin-top: 3.4cm;
    margin-bottom: 2.5cm;
    margin-left: 2.8cm;
    margin-right: 2.8cm;
    @top-left {
      content: element(mlforge-header);
      width: 100%;
    }
    @bottom-right {
      content: "Page " counter(page) " of " counter(pages);
      font-size: 8pt;
      color: #aaa;
    }
  }
  @page :first {
    /* Cover page — no running header, normal top margin */
    margin-top: 2.5cm;
    @top-left { content: none; }
  }
  #mlforge-running-header {
    position: running(mlforge-header);
    border-bottom: 2px solid #af0606;
    padding-bottom: 4px;
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  }
  
  /* ── Cover ───────────────────────── */
  .cover {
    text-align: center;
    padding-top: 80px;
    page-break-after: always;
  }
  .cover h1 {
    font-size: 26pt;
    font-weight: 700;
    letter-spacing: -0.03em;
    margin-bottom: 8px;
  }
  .cover .subtitle {
    font-size: 11pt;
    color: #6b7b8d;
    font-style: italic;
    margin-bottom: 32px;
  }
  .cover .meta-field {
    font-size: 10pt;
    margin: 4px 0;
  }
  .cover .meta-field span { font-weight: 600; }

  /* ── Section headings ────────────── */
  h2 {
    font-size: 14pt;
    font-weight: 700;
    color: #1a1a2e;
    border-bottom: 2px solid #4f86c6;
    padding-bottom: 4px;
    margin-top: 28px;
    margin-bottom: 10px;
  }
  h3 {
    font-size: 11pt;
    font-weight: 600;
    color: #4f86c6;
    margin-top: 18px;
    margin-bottom: 6px;
  }

  /* ── Body text ───────────────────── */
  p { margin: 0 0 8px 0; }

  .caption {
    font-size: 9pt;
    color: #6b7b8d;
    font-style: italic;
    margin: 4px 0 12px 0;
  }

  .warning-text {
    font-size: 9pt;
    color: #b06b00;
    background: #fef3d0;
    padding: 4px 8px;
    border-left: 3px solid #e0a84a;
    margin: 6px 0;
  }

  /* ── Tables ──────────────────────── */
  table {
    width: 100%;
    border-collapse: collapse;
    font-size: 9pt;
    margin-bottom: 16px;
  }
  thead th {
    background: #4f86c6;
    color: #ffffff;
    font-weight: 600;
    padding: 6px 10px;
    text-align: left;
  }
  tbody tr:nth-child(even) { background: #f7f9fc; }
  tbody tr:nth-child(odd)  { background: #ffffff; }
  tbody td {
    padding: 5px 10px;
    border-bottom: 1px solid #e0e6ef;
  }

  /* ── Lists ───────────────────────── */
  ul, ol {
    margin: 4px 0 12px 20px;
    font-size: 9.5pt;
  }
  li { margin-bottom: 3px; }

  /* ── Images ──────────────────────── */
  .plot-img {
    display: block;
    max-width: 100%;
    margin: 8px auto 4px;
  }

  /* ── Badge ───────────────────────── */
  .badge-good { background:#d4f5e4; color:#1a9e5c;
                padding:2px 7px; border-radius:3px; font-size:8.5pt; font-weight:600; }
  .badge-warn { background:#fef0d0; color:#b06b00;
                padding:2px 7px; border-radius:3px; font-size:8.5pt; font-weight:600; }
  .badge-poor { background:#fde8e6; color:#c0392b;
                padding:2px 7px; border-radius:3px; font-size:8.5pt; font-weight:600; }

  /* ── Page break helper ───────────── */
  .page-break { page-break-after: always; }
</style>
</head>
<body>

{{ running_header | safe }}

<div class="cover">
  <h1>{{ meta.title }}</h1>
  {{ cover_logo | safe }}
  <div class="subtitle">Generated by MLForge — Universal ML Training Platform</div>
  {% if meta.author %}
  <div class="meta-field"><span>Author:</span> {{ meta.author }}</div>{% endif %}
  {% if meta.institution %}
  <div class="meta-field"><span>Institution:</span> {{ meta.institution }}</div>{% endif %}
  <div class="meta-field"><span>Date:</span> {{ meta.date }}</div>
  <div class="meta-field"><span>Runs included:</span> {{ n_runs }}</div>
</div>

<h2>1. Introduction</h2>
<p>
  This report was generated by MLForge, a supervised regression training platform
  supporting SVR (sklearn and hand-coded implementations), Random Forest, MLP,
  Gradient Boosting, Ridge, ElasticNet, and K-Nearest Neighbours regressors.
</p>
{% if meta.notes %}
<p>{{ meta.notes }}</p>
{% endif %}

<h2>2. Dataset Summary</h2>
{% if profile %}
<table>
  <thead><tr><th>Property</th><th>Value</th></tr></thead>
  <tbody>
    <tr><td>Dataset</td><td>{{ dataset_name }}</td></tr>
    <tr><td>Rows</td><td>{{ "{:,}".format(profile.n_rows) }}</td></tr>
    <tr><td>Columns</td><td>{{ profile.n_cols }}</td></tr>
    <tr><td>Features (numeric)</td><td>{{ profile.n_features }}</td></tr>
    <tr><td>Missing values</td><td>{{ "%.1f"|format(profile.missing_pct) }}%</td></tr>
    <tr><td>Time-series</td><td>{{ "Yes" if profile.is_time_series else "No" }}</td></tr>
    <tr><td>Target column</td><td>{{ target_col }}</td></tr>
  </tbody>
</table>
{% for w in profile.warnings %}
<div class="warning-text">{{ w }}</div>
{% endfor %}
{% else %}
<p>No dataset profile available.</p>
{% endif %}

<h2>3. Model Results</h2>
{% for run in runs %}
<h3>Run #{{ run.run_id }} — {{ run.model_label }}</h3>

<table>
  <thead><tr><th>Metric</th><th>Value</th></tr></thead>
  <tbody>
    <tr><td>R²</td>  <td>{{ "%.4f"|format(run.metrics.R2)   }}</td></tr>
    <tr><td>RMSE</td><td>{{ "%.4f"|format(run.metrics.RMSE) }}</td></tr>
    <tr><td>MAE</td> <td>{{ "%.4f"|format(run.metrics.MAE)  }}</td></tr>
    <tr><td>MSE</td> <td>{{ "%.6f"|format(run.metrics.MSE)  }}</td></tr>
  </tbody>
</table>

{% set an = run.analysis %}
<p>
  <span class="{{ an.r2_badge }}">{{ an.r2_label|upper }}</span>
  &nbsp; {{ an.r2_text }}
</p>
{% if an.mae_context  %}<p class="caption">{{ an.mae_context  }}</p>{% endif %}
{% if an.rmse_context %}<p class="caption">{{ an.rmse_context }}</p>{% endif %}

{% if an.recommendations %}
<p><strong>Recommendations:</strong></p>
<ul>{% for r in an.recommendations %}<li>{{ r }}</li>{% endfor %}</ul>
{% endif %}

{% if run.best_params %}
<p class="caption">Auto-tuned parameters: {{ run.best_params }}</p>
{% endif %}

{% if run.plot_bufs.actual_vs_predicted %}
<p class="caption">Figure: Actual vs Predicted values on test set</p>
<img class="plot-img"
     src="data:image/png;base64,{{ run.plot_bufs.actual_vs_predicted }}"
     alt="Actual vs Predicted"/>
{% endif %}

{% if run.plot_bufs.residuals %}
<p class="caption">Figure: Residual distribution</p>
<img class="plot-img"
     src="data:image/png;base64,{{ run.plot_bufs.residuals }}"
     alt="Residuals"/>
{% endif %}

{% endfor %}

{% if n_runs > 1 %}
<h2>4. Runs Comparison</h2>
{% if comparison_rows %}
<table>
  <thead>
    <tr>{% for h in comparison_rows[0].keys() %}<th>{{ h }}</th>{% endfor %}</tr>
  </thead>
  <tbody>
    {% for row in comparison_rows %}
    <tr>{% for v in row.values() %}<td>{{ v }}</td>{% endfor %}</tr>
    {% endfor %}
  </tbody>
</table>
{% endif %}

{% if comp_plot_b64 %}
<p class="caption">Figure: R² comparison across all runs</p>
<img class="plot-img"
     src="data:image/png;base64,{{ comp_plot_b64 }}"
     alt="R² comparison"/>
{% endif %}
{% endif %}

<h2>{{ base_sec }}. Conclusions</h2>
<p>{{ ai_sections.conclusions }}</p>

<h2>{{ base_sec + 1 }}. Research Gaps</h2>
<p>{{ ai_sections.research_gaps }}</p>

<h2>{{ base_sec + 2 }}. Future Work</h2>
<p>{{ ai_sections.future_work }}</p>

<h2>{{ base_sec + 3 }}. References</h2>
<ol>
  {% for authors, text in references %}
  <li><strong>{{ authors }}</strong> — {{ text }}</li>
  {% endfor %}
</ol>

</body>
</html>
"""


def _buf_to_b64(buf) -> str | None:
    """Convert a BytesIO PNG buffer to a base64 string for embedding in HTML."""
    if buf is None:
        return None
    buf.seek(0)
    return base64.b64encode(buf.read()).decode("utf-8")


def build_pdf(
    runs:            list[dict],
    report_cfg:      dict,
    dataset_profile: dict,
    ai_sections:     dict | None = None,
) -> tuple[bytes, str]:
    """
    Build a PDF report and return (bytes, filename).
    """
    payload = build_report_payload(runs, report_cfg, dataset_profile, ai_sections)

    # Encode all plot buffers as base64 for inline HTML
    for run in payload["runs"]:
        bufs = run.get("plot_bufs", {})
        run["plot_bufs"] = {k: _buf_to_b64(v) for k, v in bufs.items()}

    comp_plot_b64 = _buf_to_b64(payload.get("comp_plot_buf"))

    dataset_name = runs[0].get("dataset_name", "Unknown") if runs else "Unknown"
    target_col   = runs[0].get("target_col",   "target")  if runs else "target"
    base_sec     = 5 if payload["n_runs"] > 1 else 4

    # Render HTML template
    tmpl     = Template(_TEMPLATE)
    # CHANGE 5: Added running_header and cover_logo to render call
    html_str = tmpl.render(
        meta            = payload["meta"],
        profile         = type("P", (), payload["profile"])() if payload["profile"] else None,
        dataset_name    = dataset_name,
        target_col      = target_col,
        runs            = payload["runs"],
        comparison_rows = payload["comparison_rows"],
        comp_plot_b64   = comp_plot_b64,
        best_run        = payload["best_run"],
        n_runs          = payload["n_runs"],
        ai_sections     = payload["ai_sections"],
        references      = payload["references"],
        base_sec        = base_sec,
        running_header  = pdf_running_header_html(),
        cover_logo      = pdf_cover_logo_html(size_px=110),
    )

    # WeasyPrint → PDF
    pdf_bytes = HTML(string=html_str).write_pdf()

    meta       = payload["meta"]
    safe_title = meta.get("title", "MLForge_Report").replace(" ", "_")
    filename   = f"{safe_title}_{meta.get('date', 'report').replace(' ', '_')}.pdf"

    return pdf_bytes, filename